services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: local
    container_name: web-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "main.go"]
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.4
    container_name: auth_db
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    image: redis:7.4
    container_name: auth_redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
